const lang = {
  'en-US': {
    nav: {
      home: 'Home',
      account: 'Account',
    },
    index: {
      trending: 'Trending',
      now: 'Now',
      new: 'New',
      releases: 'Releases',
    },
    movie: {
      submit_reivew: 'Submit Review',
      see_all_review: 'See All Review',
      cast: 'Cast',
      crew: 'Crew',
      filmography: 'Filmography',
      born: 'Born',
      died: 'Died',
      from: 'From',
      trailer: 'Watch Trailer',
    },
    save: 'Save',
    remove: 'Remove',
    account: {
      login: 'Log In',
      signup: 'Sign Up',
      submit: 'Submit',
      collapse: 'Collapse',
      my_account: 'My Account',
      my_reviews: 'My Reviews',
      saved_reviews: 'Saved Reviews',
      saved_movies: 'Saved Movies',
      logout: 'Log out',
      username: 'username',
      email: 'email',
      update_image: 'Update Image',
    },
    review: {
      title: 'Title',
      content: 'Content',
      image: 'Image',
      update: 'Update',
      no_review: 'Currently no review',
      spoiler: 'Spoiler Alert',
    },
    upload: 'Upload',
    edit: 'Edit',
    delete: 'Delete',
    cannot_find: "Cannot Find the Movie You're Searching For",
    404: 'Looks like the page you were looking for is no longer here',
  },
  'zh-TW': {
    nav: {
      home: '首頁',
      account: '帳號',
    },
    index: {
      trending: '熱門',
      now: '電影',
      new: '最新',
      releases: '上映',
    },
    movie: {
      submit_reivew: '上傳評論',
      see_all_review: '看所有評論',
      cast: '演員',
      crew: '工作人員',
      filmography: '其他作品',
      born: '出生',
      died: '過世',
      from: '來自',
      trailer: '預告片',
    },
    save: '收藏',
    remove: '移除',
    account: {
      login: '登入',
      signup: '註冊',
      submit: '提交',
      collapse: '收合',
      my_account: '我的帳號',
      my_reviews: '我的評論',
      saved_reviews: '收藏評論',
      saved_movies: '收藏電影',
      logout: '登出',
      username: '使用者名稱',
      email: '電子信箱',
      update_image: '更新頭像',
    },
    review: {
      title: '標題',
      content: '內容',
      image: '圖片',
      update: '更新',
      no_review: '目前沒有評論',
      spoiler: '防雷提示',
    },
    upload: '上傳',
    edit: '編輯',
    delete: '刪除',
    cannot_find: '找不到此電影',
    404: '頁面不存在',
  },
  'fr-FR': {
    nav: {
      home: 'Accueil',
      account: 'Mon compte',
    },
    index: {
      trending: 'En',
      now: 'Salles',
      new: 'Dernières',
      releases: 'News',
    },
    movie: {
      submit_reivew: 'Poster un commentaire',
      see_all_review: 'Voir tous les commentaires',
      cast: 'Acteurs et Actrices',
      crew: "l'équipe",
      filmography: 'Filmographie',
      born: 'Né',
      died: 'Mort',
      from: 'De',
      trailer: 'Bandes-Annonces',
    },
    save: 'Envie de voir',
    remove: 'Retirer',
    account: {
      login: 'Se connecter',
      signup: "S'inscrire",
      submit: 'Soumettre',
      collapse: 'Effondrement',
      my_account: 'Mon compte',
      my_reviews: 'Mes commentaires',
      saved_reviews: 'Commentaires Enregistrés',
      saved_movies: 'Films Enregistrés',
      logout: 'Se déconnecter',
      username: 'Nom',
      email: 'e-mail',
      update_image: "Réviser l'image",
    },
    review: {
      title: 'Titre',
      content: 'Contenu',
      image: 'Image',
      update: 'Réviser',
      no_review: 'Pas de commentaire pour le moment',
      spoiler: 'Alerte Spoiler',
    },
    upload: 'Télécharger',
    edit: 'Éditer',
    delete: 'Effacer',
    cannot_find: 'Impossible de trouver le film que vous recherchez',
    404: "La page que vous recherchez n'existe plus",
  },
};

module.exports = lang;
